from building import *
import os

cwd = GetCurrentDir()

# Header-only layer (transport.h): no sources here, but export the include
# path and pick up per-link subdirectories (usb/ ...).
CPPDEFINES = ['WLH_LOG_BACKEND_RTT_ULOG']

group = DefineGroup('wlh_transports', [], depend=[''], CPPPATH=[cwd], CPPDEFINES=CPPDEFINES)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
